### ISSUE TITLE
NCPI FHIR Model Repo Updates 

### ISSUE THREAD

**Issue by znatty22** [d3b-center/clinical-data-flow#111]
- [x] Add an FHIR ingest plugin for the NCPI FHIR model (@fiendish )
- [ ] Add the integration test framework to this repo (@znatty22 
- [ ] Add a Jenkins model deployment pipeline (nice to have, @znatty22 )

**Comment by fiendish** [comment]
The NCPI model repo only has a patient resource. Where are the rest?

**Comment by znatty22** [comment]
@fiendish  We don't have any yet
