### ISSUE TITLE
Enable searching of resources by added attributes (extensions)

### ISSUE THREAD

**Issue by znatty22** [d3b-center/clinical-data-flow#34]
**Autogenerate SearchParameters for a given set of extensions**
A user cannot search for resources by added attributes (extensions) unless SearchParameter resources have been created and loaded into the server for those extensions. 

For example the Phenopackets FHIR model has an extension called `karyotypic-sex`. The `karyotypic-sex` extension defines a new attribute on the Patient resource. Users cannot do searches like this: `/Patient?karyotypic-sex=XY` right now because the FHIR server does not have a SearchParameter for it.

Add a new CLI command to the kf-model-fhir CLI to generate SearchParameters for a file or directory containing extensions.

**Make PR to add SearchParameter files to kf-model-fhir**

- Create a branch off of `kf-model-fhir/add-phenopackets-model` and make your PR against that branch
- All SearchParameters should go in https://github.com/kids-first/kf-model-fhir/tree/add-phenopackets-model/site_root/source/resources

**Load SearchParameters into FHIR server**
Load the generated SearchParameters into the FHIR server

**Comment by fiendish** [comment]
first pass naive generator at https://github.com/kids-first/kf-model-fhir/blob/spgenerator/scripts/search_parameter_generator.py

**Comment by znatty22** [comment]
Closing since this is complete and just has to be merged into master branch

**Comment by znatty22** [comment]
Reopening because this still needs to be completed
