### ISSUE TITLE
Document feedback on FHIR Phenopackets and lessons learned on FHIR Ingest

### ISSUE THREAD

**Issue by znatty22** [d3b-center/clinical-data-flow#39]
Create a file called `lessons_learned.md` in https://github.com/d3b-center/clinical-data-flow/tree/master/docs. Make a PR against the clinical-data-flow repo. We can move this somewhere else if we find a better place for it. 

The document should include issues with or modifications needed on the FHIR Phenopackets model. One goal of the document is to communicate the FHIR Phenopackets issues in the GA4GH phenopackets slack channel and create Github issues on the Phenopackets on FHIR repository.

**Comment by fiendish** [comment]
I've added https://github.com/kids-first/kf-model-fhir/blob/questions/docs/questions.md
Make edits to it as appropriate.

I didn't want to call it "lessons learned", because there are a bunch of things we don't have answers to yet.

**Comment by allisonheath** [comment]
Can we call it "Feedback and Questions" ?

**Comment by fiendish** [comment]
ok https://github.com/kids-first/kf-model-fhir/blob/questions/docs/feedback_and_questions.md
