### ISSUE TITLE
Kids First Data Service to FHIR mapping spreadsheet: PT, BS 

### ISSUE THREAD

**Issue by znatty22** [d3b-center/clinical-data-flow#43]
Create a spreadsheet that captures which Kids First entities we are modeling in the [MVP](https://github.com/d3b-center/clinical-data-flow/issues/44), which FHIR resources they map to, the name and types of the Kids First attributes, and which FHIR 
attributes or extensions the they map to. 

Something like this:

Participant tables:

| Kids First Entity | Kids First Attribute | Kids First Attr Type | FHIR Base Type | FHIR Attr | FHIR Type |
----------------- | ------------------ | ------------------- | ---------------- | --------- | ---------- | 
Participant | is_proband | boolean | Patient | None | N/A
Participant | gender | enum | Patient | gender | code
Phenotype | hpo_id | string | Observation | code.codings.0.code | CodeableConcept.Coding.code

Need extensions for these attributes because they are not part of :

We need to know if extensions exist for these and where they are or if we need to create new extensions.

| Kids First Entity | Kids First Attribute | Kids First Attr Type | FHIR Base Type | FHIR Extension | FHIR Type |
----------------- | ------------------ | ------------------- | ---------------- | --------- | ---------- | 
Participant | ethnicity | boolean | Patient | None | N/A

**Comment by liberaliscomputing** [comment]
The initial pass mapping participant and biospecimen to Patient and Specimen is available at the HL7 FHIR v.4.0.1 tab at https://docs.google.com/spreadsheets/d/19tQnE75UzvP_k29D-QprbsJ-6ZO2PdUmKPiWHKkcTEg/edit?usp=sharing.

**Comment by znatty22** [comment]
Closing this since initial spreadsheet has been created. Will create new issues to complete the spreadsheet.
