### ISSUE TITLE
Redesign parts of Dashboard UX 

### ISSUE THREAD

**Issue by znatty22** [d3b-center/clinical-data-flow#65]
Now that we have a better understanding of what's what in FHIR, it might be time to think about refactoring the UX on parts of the dashboard. Some views to think about:

1. Home page 
- Is there a better way to organize resource tiles?
- Should we include some summary stats of the most common resources on the home page?

2. Resource type summary page
- How do we better organize the counts, enum pie charts, and bar charts

**Comment by abgeorge7** [comment]
Done - located here: https://projects.invisionapp.com/d/main#/console/19790184/414357519/preview
