### ISSUE TITLE
Contact Smile CDR about various issues

### ISSUE THREAD

**Issue by znatty22** [d3b-center/clinical-data-flow#96]
- [x] Talk to smile cdr about not being able to get StructureDefinitions for base resources
- [x] Test new release, respond to tickets on the following issues:
    - [x] Snapshot generation (https://github.com/kids-first/kf-api-fhir-service/issues/35)
    - [x] `valueset` search parameter (https://github.com/kids-first/kf-api-fhir-service/issues/30)
- [x] Talk to smile cdr about connecting to an external terminology server. docs describe how to upload codesystems but not connect to another server.
- [x] Talk to smile cdr about that the new images (`2020.08.PRE-16` and `2020.05.R01` a.k.a. Labrador) fail to load resources containing `code`, `Coding`, `CodeableConcept`, object, and/or array of objects, throwing the following error:

```json
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "invalid",
      "diagnostics": "[8b812bcf-957e-45fc-bb4a-794cf527a88f]: If the code parameter is provided, the system parameter must also be provided."
    }
  ]
}
```

**Comment by abgeorge7** [comment]
Smile CDR's response: seems like checkbox 1 is a setting, and the functionality is not missing:
https://smilecdr.freshdesk.com/support/tickets/461

**Comment by liberaliscomputing** [comment]
Per the last issue: https://smilecdr.freshdesk.com/support/tickets/486
